$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: greek-dam-training
description: Environment for Greek DAM forecasting training jobs
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
conda_file: ./conda_environment.yml